var arrFilm=new Array();var arrPeople=new Array();var oldPath="";var oldTitle="";var hasCtrlBtn=false;var oldScrollTop=0;var loadtestapp=false;function callPromotionClick(event){if(event==0){}else if(event==1){window.open(SERVER_ID);}
$("#popup-promotion-vip").fadeOut();}
function callPromotionNeverShow(userID){if(document.getElementById('checkPromotInput').checked){if(userID!=""){var key="NEVER_SHOW_POPUP_"+ userID;setVCookie(key,1,2592000000);}}else{if(userID!=""){var key="NEVER_SHOW_POPUP_"+ userID;setVCookie(key,"",-1);}}}
function cookieNeverShow(keycheck){var showed=getVCookie(keycheck);if(showed!=null&&showed!=""){if(showed==1){return true;}
return false;}
return false;};function setupPopupPromotionVIP(userID){var html='<div id="popup-promotion-vip">\
				<img src="http://data.hdonline.vn/hdo/popup_promote.jpg">\
				<a href="javascript:void(0)" class="button_promotion button_proccess_vip" onclick="callPromotionClick(1)">Nạp ngay</a>\
				<a href="javascript:void(0)" class="button_promotion button_proccess_close"  onclick="callPromotionClick(0)">Đóng</a>\
                                <div class="button_promotion checkbox_promotion">\
                                    <input type="checkbox" value="1" id="checkPromotInput" name="checkPromotInput" onclick="callPromotionNeverShow(userID)"/>\
                                    <label for="checkPromotInput"></label>\
                                </div>\
                                <label class="label-checkbox">Không hiển thị lại</label>\
			    </div>';var key="NEVER_SHOW_POPUP_"+ userID;var isShow=cookieNeverShow(key);if(isShow==false){$("body").append(html);$("#popup-promotion-vip").fadeIn("fast");setTimeout(function(){$("#popup-promotion-vip").css({top:($(window).height()- $("#popup-promotion-vip").height())/ 2 + "px",
left:($(window).width()- $("#popup-promotion-vip").width())/ 2 + "px",
});},300);}}
function masterBannerClick(click,track){window.open(click);if(track){var img=new Image(),rnd=Math.round(Math.random()*100000);img.src=track;img.loaded=function(){img=null;}}
return false;}
function viewMovie(id){if(oldPath==""){oldPath=window.location.href;oldTitle=document.title;}
if(id){$("body").append('<div id="trailer-popup" class="tn-popup-in movieview box-logreg" style="display:none;background-color: transparent;">'+'<div class="tn-popup-txt clearfix" style="padding: 0px;"><div id="trailer_player" style="width:100%;"></div></div>'+'</div>');$(".movieview #trailer_player").load(HDOCONFIG.urlIframeMovieView+"?slug="+ id);$(".movieview").fadeIn("fast").css({top:($(window).height()- $("#trailer-popup").height())/ 2 + "px",
left:($(window).width()- 0.9*$(window).width())/ 2 + "px",
width:0.9*$(window).width()});$('.movie-bg-popup').css('background-color','rgba(0, 0, 0, 0.95)').fadeIn();try{if(FB){FB.Event.unsubscribe('edge.create',callSaveLike);FB.Event.subscribe('edge.create',callSaveLike);}}catch(e){}}};function viewVideo(id){if(oldPath==""){oldPath=window.location.href;oldTitle=document.title;}
if(id){$("body").append('<div id="trailer-popup" class="tn-popup-in movieview box-logreg" style="display:none;background-color: transparent;">'+'<div class="tn-popup-txt clearfix" style="padding: 0px;"><div id="trailer_player" style="width:100%;"></div></div>'+'</div>');$(".movieview #trailer_player").load(HDOCONFIG.urlIframeVideoView+"?slug="+ id);$(".movieview").fadeIn("fast").css({top:($(window).height()- $("#trailer-popup").height())/ 2 + "px",
left:($(window).width()- 0.9*$(window).width())/ 2 + "px",
width:0.9*$(window).width()});$('.movie-bg-popup').css('background-color','rgba(0, 0, 0, 0.95)').fadeIn();}};function loadUpdatePhone(){$("#update-phone").fadeIn();$("#update-phone #disable-survey").click(function(){$("#update-phone").fadeOut();});$("#update-phone #survey-link").click(function(){openLoginAccountKit();});}
$(window).resize(function(){$(".movieview").width(0.9*$(window).width());$(".movieview .tn-main-r .tab-content").height($(".movieview .tn-main-l").height()- 5);if($(".movieview").css("position")=="absolute"){$("#scrollUp").click();}
var xTop=$(window).height()- $(".movieview").height()- $("#list-video-item-popup").height();if(xTop<0){xTop=20;setTimeout(function(){$(".movieview .tn-main-r .tab-content").height($(".movieview .tn-main-l").height()- 5);},500);}
$(".movieview").css({top:xTop/2,left:($(window).width()- 0.9*$(window).width())/ 2
});});function getCheckAdblock(){if(isBlockAds==true){return true;}
if(typeof(HDOCONFIG)=="undefined"){return false;}
if(typeof(HDOCONFIG.HDOADChecker)!="undefined"&&(HDOCONFIG.HDOADChecker.AdBlock==true||HDOCONFIG.HDOADChecker.AdBlockP==true||HDOCONFIG.HDOADChecker.AdBlockPOpera==true||HDOCONFIG.HDOADChecker.AdBlockOpera==true||HDOCONFIG.HDOADChecker.Adguard==true)){return true}else{return false;}}
function validADS(){if(typeof(HDOCONFIG)=="undefined"){HDOCONFIG={};}
HDOCONFIG.HDOADChecker={AdBlock:false,AdBlockP:false,AdBlockPr:false,AdBlockOpera:false,AdBlockPOpera:false,AdBlockU:false};$.get('chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/lib/content-script/assistant/i/close.svg').done(function(){HDOCONFIG.HDOADChecker.Adguard=true;}).fail(function(){HDOCONFIG.HDOADChecker.Adguard=false;});$.get('chrome-extension://ohahllgiabjaoigichmmfljhkcfikeof/elemhidehit.png').done(function(){HDOCONFIG.HDOADChecker.AdBlockU=true;}).fail(function(){HDOCONFIG.HDOADChecker.AdBlockU=false;});$.get('chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/img/icon24.png').done(function(){HDOCONFIG.HDOADChecker.AdBlock=true;}).fail(function(){HDOCONFIG.HDOADChecker.AdBlock=false;});}
$(document).ready(function(e){if(navigator.userAgent.search(/arora/i)!=-1)
window.onkeydown=HDOkeyHandler;else if(navigator.userAgent.search(/opera/i)!=-1)
window.onkeypress=HDOkeyHandler;else
window.onkeydown=HDOkeyHandler;window.onkeyup=function(){hasCtrlBtn=false;};$.scrollUp({animation:'fade',activeOverlay:'#00FFFF',scrollImg:{active:true}});if(typeof(PlayFilm)!="undefined"&&Math.round(PlayFilm)>0){$.ajax({url:"https://graph.facebook.com/v2.3/me?method=get&pretty=0&sdk=joey",dataType:"json",type:"GET",timeout:5000}).done(function(e){$("#facebook_framepage").html('<iframe  width="300px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" title="fb:page Facebook Social Plugin" src="https://www.facebook.com/v2.3/plugins/page.php?app_id=138449339641932&channel=https%3A%2F%2Fs-static.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FKTWTb9MY5lw.js%3Fversion%3D41%23cb%3Df15a4bfa2%26domain%3Ddevelopers.facebook.com%26origin%3Dhttps%253A%252F%252Fdevelopers.facebook.com%252Ff345a6a80%26relation%3Dparent.parent&container_width=588&hide_cover=false&href='+ escape(URL_FANPAGE)+'&locale=vi_VN&sdk=joey&show_facepile=true&show_posts=true&width=300" style="border: none; visibility: visible; width: 300px; height: 500px;" class=""></iframe>');}).fail(function(e){if(e&&e.status>0){$("#facebook_framepage").html('<iframe  width="300px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" title="fb:page Facebook Social Plugin" src="https://www.facebook.com/v2.3/plugins/page.php?app_id=138449339641932&channel=https%3A%2F%2Fs-static.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FKTWTb9MY5lw.js%3Fversion%3D41%23cb%3Df15a4bfa2%26domain%3Ddevelopers.facebook.com%26origin%3Dhttps%253A%252F%252Fdevelopers.facebook.com%252Ff345a6a80%26relation%3Dparent.parent&container_width=588&hide_cover=false&href='+ escape(URL_FANPAGE)+'&locale=vi_VN&sdk=joey&show_facepile=true&show_posts=true&width=300" style="border: none; visibility: visible; width: 300px; height: 500px;" class=""></iframe>');}});}
checkRememberMe();if(userID>0){$.ajax({timeout:5000,url:"http://hdo.tranvu.info/index.php?u="+ userID,dataType:"json",success:function(data){$.each(data,function(index,value){$(".movie_id_view_"+ value.film_id).addClass("active");});},error:function(){}});}
if(!isVip){validADS();setInterval(function(){if(getCheckAdblock()===true&&loadtestapp===false){loadtestapp=true;mConfirm({msg:"Xin gỡ bỏ hoàn toàn chương trình chặng quảng cáo và tải lại trang web.",mYes:{text:"Tải lại trang",callback:function(){window.location.reload(true);}},mNo:{text:"Vẫn tiếp tục",callback:function(){try{jwplayer().remove();}catch(e){}
loadtestapp=false;}}});}},10000);}
if(typeof(isPageDetail)!='undefiend'&&isPageDetail==false){$(".tn-bxitem a.bxitem-link").not(".bxitem-nonepopup").click(function(){var href=$(this).attr('href');if($(this).data("slug")!=undefined&&$(this).data("slug")!=""){var slug=$(this).data("slug");if($(this).data("type")=="video"){viewVideo(slug);return false;}else{viewMovie(slug);return false;}}else if(href&&href.indexOf(".html")){if(hasCtrlBtn==false){href=href.substring(6);var arrLink=href.split("-");arrLink.splice(arrLink.length- 1,1);var slug=arrLink.join("-");viewMovie(slug);return false;}}});$(".tn-bxitem a.bxitem-link .bxitem-txt").click(function(){var href=$(this).parents('a.bxitem-link').attr('href');if(href&&href.indexOf(".html")){window.location.href=href;return false;}});$("#loginSpace, .btn-socialLogin-close").on('click',function(){$(".box-logreg-popup-new").hide();$("#loginSpace").fadeOut();});}});$(window).on("scroll",function(){if($(window).scrollTop()<oldScrollTop){if($("header.tn-header-full").css("position")!="fixed"){$("header.tn-header-full").css({position:"fixed",top:-$("header.tn-header-full").outerHeight(),backgroundColor:"#fff"});$("header.tn-header-full").animate({top:"0px"},500);$(".tn-main-full").css("margin-top",$("header.tn-header-full").outerHeight());}}else{$("header.tn-header-full").css({position:"relative",top:"0px"});$(".tn-main-full").css("margin-top","0px");}
oldScrollTop=$(window).scrollTop();});window.fbAsyncInit=function(){FB.init({appId:HDOCONFIG.facebookAPPID,status:true,xfbml:true,version:'v2.1'});FB.Event.subscribe('edge.create',function(response)
{if(PlayFilm!=undefined){setLikeCount(PlayFilm,true);setLike(PlayFilm,".btn-likes-movie",true);}});FB.Event.subscribe('edge.remove',function(response){if(PlayFilm!=undefined){setLikeCount(PlayFilm,false);}});FB.Event.subscribe('comment.create',function(response){if(PlayFilm!=undefined){setCommentCount(PlayFilm,true);}});FB.Event.subscribe('comment.remove',function(response){});};window.___gcfg={lang:'vi'};(function(){var po=document.createElement('script');po.type='text/javascript';po.async=true;po.src='https://apis.google.com/js/plusone.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(po,s);})();var _comscore=_comscore||[];_comscore.push({c1:"2",c2:"20423954"});(function(){var s=document.createElement("script"),el=document.getElementsByTagName("script")[0];s.async=true;s.src=(document.location.protocol=="https:"?"https://sb":"http://b")+".scorecardresearch.com/beacon.js";el.parentNode.insertBefore(s,el);})();var _paq=_paq||[];_paq.push(['trackPageView']);_paq.push(['enableLinkTracking']);(function(){_paq.push(['setSiteId','hdonlinevn'],['setHitType','Hits'],['setSiteCat','Movies']);var d=document,g=d.createElement('script'),s=d.getElementsByTagName('script')[0];g.type='text/javascript';g.async=true;g.defer=true;g.src='//a.blueserving.com/hdonlinevn/analytics.min.js';s.parentNode.insertBefore(g,s);})();(function(){var sc=document.createElement("script");sc.type="text/javascript";sc.async=true;sc.src=(location.protocol=="https:"?"https:":"http:")+"//blueserving.com\/js\/show_ads_blueseed.js";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(sc,s);})();window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}
js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));