var preSlotOneImp=true;var preSlotOneStr=true;var isMovieDetailPage=true;var intLoadScroll;var objDataVideoDeatail=[];var arrSlideScreenshot=[];var arrSimilar={};function playerSendContact(){showBroken();}
function vpluginadstracking($event,$id){}
function resize_player(player,resize)
{var jw5="";if($("#"+player+"_wrapper").length>0){jw5="_wrapper";}
if(resize=="min"||resize=="_min"){$(".player-container #"+player+jw5).animate({width:"925px"},200);$(".player-container #player, .player-container #player #"+player+jw5).animate({height:"520px"},200);}else{$(".player-container #"+player+jw5).animate({width:"1200px"},200);$(".player-container #player, .player-container #player #"+player+jw5).animate({height:"675px"},200);};}
function callScroll(){try{if($(".tn-main-r").height()>$(".tn-main-l").height()){var objScroll=$(".tn-main-l");var leftPad=$('.div-content-table').offset().left+ $('.tn-main-r').outerWidth()+ 12;var leftBottom=$('.tn-main-r').outerWidth()+ 10;$(".tn-main-r").css({position:"relative",top:"0px",bottom:"auto",left:"auto"});}else{var objScroll=$(".tn-main-r");var leftPad=leftBottom="auto";$(".tn-main-l").css({position:"relative",top:"0px",bottom:"auto",left:"auto"});}
if($(window).scrollTop()>objScroll.height()&&$(window).scrollTop()>$('.tn-main2').offset().top){if($(window).height()<objScroll.height()){objScroll.css({position:"fixed",top:"auto",bottom:"0px",left:leftPad});}else if($(window).scrollTop()>$('.div-content-table').offset().top){objScroll.css({position:"fixed",top:"0px",bottom:"auto",left:leftPad});}
if($(window).scrollTop()+ $(window).height()>=$(document).height()- $('.tn-footer-full').height()){if($(window).height()<objScroll.height()){objScroll.css({position:"absolute",top:"auto",bottom:"0px",left:leftBottom});}else if($(window).scrollTop()+ $(window).height()+ objScroll.height()>=$(document).height()- $('.tn-footer-full').height()){objScroll.css({position:"absolute",top:"auto",bottom:"0px",left:leftBottom});}else{objScroll.css({position:"fixed",top:"0px",bottom:"auto",left:leftPad});}}}else{objScroll.css({position:"relative",top:"0px",bottom:"auto",left:"auto"});}}catch(e){}}
function callResize(){if($(window).width()>$(".player-container").width()+ $(".filminfo-social").width()){$(".filminfo-social").show();}else{$(".filminfo-social").hide();}}
function intVideoScrollDetail(){var html="";$.ajax({url:HDOCONFIG.urlGetMoreVideo,type:"GET",dataType:"json",cache:false,data:{film:PlayFilm},}).done(function(e){if(e.data&&e.data.length>0){$.each(e.data,function(index,value){var name=value.title;if(name.length>20){name=name.substring(0,17)+"...";}
objDataVideoDeatail.push(value);html+='<div class="item-video"><a data-film="'+ PlayFilm+'" onclick="viewVideo(\''+ value.slug+'\');return false;" data-index="'+(objDataVideoDeatail.length- 1)+'" data-id="'+ value.id+'" title="'+ value.title+'" data-slug="'+ value.slug+'" data-type="video" class="send-video-player bxitem-link" href="'+ value.url+'"><img src="'+ value.image+'"/><span class="bxitem-txt video-title">'+ name+'</span><span class="bxitem-over_play"></span></a></div>';});$('#carousel-video-detail').html(html);$("#list-video-item-detail").fadeIn();$('#carousel-video-detail').carouFredSel({items:{width:200,visible:{min:3,max:8}},direction:"left",align:'center',width:"100%",responsive:false,infinite:false,circular:true,scroll:{items:4,duration:400},next:{button:"#slider-button-detail-next",key:"right"},prev:{button:"#slider-button-detail-prev",key:"left"},auto:{play:false}});}});}
$(window).resize(function(){callResize();});$(window).scroll(function(){callScroll();});$(window).load(function(){setViewFilm(PlayFilm);var startPlus=filmView- 2000;if(startPlus>0){var startPlay=filmView- 5000;if(startPlay<0){startPlay=0;}
var filmPlus=setInterval(function(){startPlay+=Math.round(28);$(".film_view_count").html(numberWithCommas(startPlay));if(startPlay>=startPlus){clearInterval(filmPlus);$(".film_view_count").html(numberWithCommas(startPlus));filmPlus=setInterval(function(){startPlus++;if(startPlus>filmView){clearInterval(filmPlus);}else{$(".film_view_count").html(numberWithCommas(startPlus));}},200);}},50);}else{$(".film_view_count").html(numberWithCommas(filmView));}});$(document).ready(function(){$(".screenshot-slide-popup").each(function(){arrSlideScreenshot.push($(this).attr('src'));});$('.screenshotview').cycle({slides:".media-screen",pagerTemplate:"",prev:"#screenshot-prev",next:"#screenshot-next",timeout:8000,speed:200});$('.movie-screens-bg').click(function(){$('.screenshotview, .movie-screens-bg').fadeOut();});$(".screenshot-slide-popup").click(function(){var src=$(this).attr('src');$.each(arrSlideScreenshot,function(index,value){if(value==src){$(".screenshotview").cycle('goto',index);return false;}});$(".screenshotview").css({top:($(window).height()- $(".screenshotview").height())/2,
left:($(window).width()- $(".screenshotview").width())/2
}).fadeIn("fast");$('.movie-screens-bg').css('background-color','rgba(0, 0, 0, 0.95)').fadeIn();});$('.key_similar_id').each(function(index,value){if(arrSimilar[$(this).data('id')]){$(this).remove();}
arrSimilar[$(this).data('id')]=true;});$('.tn-contentmt').readmore({speed:75,lessLink:'<a href="javascript:void(0);" class="center-block text-right">Thu gọn</a>',moreLink:'<a href="javascript:void(0);" class="center-block text-right">Xem thêm..</a>',collapsedHeight:60});$('.actor-movie-list').readmore({speed:75,lessLink:'<a href="javascript:void(0);" class="center-block text-right">Thu gọn</a>',moreLink:'<a href="javascript:void(0);" class="center-block text-right">Xem thêm..</a>'});$("#closeFeedback").click(function(e){e.preventDefault();$(".feedbackMovie").fadeOut();});$(".sendFeedback").click(function(e){e.preventDefault();sendFeedBack();});$('.hideall').hide();$.lockfixed(".float-left",{offset:{top:10,bottom:$(document).height()- $('.tn-footer-full').offset().top+ 10}});$.lockfixed(".float-right",{offset:{top:10,bottom:$(document).height()- $('.tn-footer-full').offset().top+ 10}});jRateConfig.onChange=function(rating){$('#jrate-change').text(rating+"/10");};jRateConfig.onSet=function(rating){if(isLogin){$.ajax({url:HDOCONFIG.urlRate,type:"GET",dataType:"json",cache:false,data:{film:PlayFilm,vote:rating},}).done(function(e){jRateConfig.onSet=function(){};jRateConfig.readOnly=true;jRateConfig.rating=e.rating;}).fail(function(e){});}else{openLogin();}}
$("#jRate").jRate(jRateConfig);callScroll();callResize();intVideoScrollDetail();});